apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    name: hello
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: hello
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    name: hello
  name: hello
  annotations:
    federation.alpha.kubernetes.io/cluster-selector: '[{"key": "location", "operator": "In", "values": ["europe"]}]
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - image: hjacobs/tiny-docker-http-test
        name: helloworld
        ports:
        - containerPort: 8080
          name: http-server